extends SceneTree
## Exact binary-float equality against independently read GLB input, after .res reload
## and real UnitView selection. Input is generated by tools/asuna_animation/prepare.py.
const Guard=preload("res://scripts/native_animation_library.gd")
var failures:=0
var checks:=0
func ck(ok:bool,label:String)->void:
 checks+=1
 if not ok:failures+=1;printerr("FAIL: ",label)
func _initialize()->void:call_deferred("run")
func run()->void:
 var args:PackedStringArray=OS.get_cmdline_user_args()
 if args.size()!=1:printerr("Expected prepared source payload JSON");quit(2);return
 var source:Dictionary=JSON.parse_string(FileAccess.get_file_as_string(args[0]))
 var profile:Dictionary=JSON.parse_string(FileAccess.get_file_as_string("res://data/character-presentations.json")).asuna
 ck(source.source_glb_sha256==profile.source_glb_sha256,"matching source input")
 var view=load("res://scripts/unit_view.gd").new();root.add_child(view)
 view.setup({"id":91,"character_id":"asuna","team":0,"cell":Vector2.ZERO,"range":3.0,"attack_ticks":60,"presentation":profile},{},7)
 ck(view.player!=null and view.diagnostics().warnings.is_empty(),"real profile selects library without warnings")
 if view.player==null:quit(1);return
 var library:AnimationLibrary=view.player.get_animation_library("")
 var imported:Node3D=load(profile.model_path).instantiate();root.add_child(imported)
 var original:AnimationLibrary=imported.find_child("AnimationPlayer",true,false).get_animation_library("")
 var total:int=0;var restored:int=0;var constants:int=0
 var kinds:Dictionary={1:"translation",2:"rotation",3:"scale"}
 for name in library.get_animation_list():
  var clip:Animation=library.get_animation(name)
  var raw:Animation=original.get_animation(name)
  ck(clip.length==raw.length and clip.get_track_count()==raw.get_track_count(),"length/track count unchanged "+name)
  for i in clip.get_track_count():
   var path:NodePath=clip.track_get_path(i);var type:int=clip.track_get_type(i)
   ck(path==raw.track_get_path(i) and type==raw.track_get_type(i),"track path/type unchanged")
   ck(clip.track_get_interpolation_type(i)==raw.track_get_interpolation_type(i) and clip.track_is_enabled(i)==raw.track_is_enabled(i) and clip.track_get_interpolation_loop_wrap(i)==raw.track_get_interpolation_loop_wrap(i),"track options unchanged")
   var leaf:String=String(path.get_subname(0)) if path.get_subname_count()>0 else String(path.get_name(path.get_name_count()-1))
   var identity:String=leaf+"|"+kinds[type]
   if source.clips[String(name)].channels.has(identity):
    var channel:Dictionary=source.clips[String(name)].channels[identity]
    var times:PackedFloat32Array=PackedFloat32Array(channel.times)
    ck(clip.track_get_key_count(i)==times.size(),"exact restored key count")
    for k in mini(clip.track_get_key_count(i),times.size()):
     var row:Array=channel.values[k]
     var expected:Variant=Quaternion(row[0],row[1],row[2],row[3]) if type==2 else Vector3(row[0],row[1],row[2])
     ck(clip.track_get_key_time(i,k)==times[k] and clip.track_get_key_value(i,k)==expected,"source key time/value bit-exact after native reload and UnitView copy")
     total+=1
    restored+=1
   else:
    ck(clip.track_get_key_count(i)==raw.track_get_key_count(i),"generated constant count unchanged")
    for k in clip.track_get_key_count(i):ck(clip.track_get_key_time(i,k)==raw.track_get_key_time(i,k) and clip.track_get_key_value(i,k)==raw.track_get_key_value(i,k),"generated constant remains exactly imported")
    constants+=1
 ck(total==262970 and restored==1818 and constants==18,"complete audited restoration counts")
 print("ASUNA EXACT KEY CHECKS=",checks," FAILURES=",failures," SOURCE_KEYS=",total," RESTORED_TRACKS=",restored," GENERATED_CONSTANTS=",constants)
 imported.free();view.free();quit(1 if failures else 0)
