extends SceneTree
var checks:=0
var failures:=0
var units:Array=[{"id":1,"character_id":"mutsuki","team":0,"hp":100},{"id":2,"character_id":"mutsuki","team":1,"hp":100}]
func ck(ok:bool,label:String)->void:
 checks+=1
 if not ok:failures+=1;push_error(label)
func _initialize()->void:call_deferred("run")
func event(kind:String,id:int,tick:int,extra:Dictionary={})->Dictionary:
 var value:Dictionary={"type":kind,"mine_id":id,"actor_id":1,"tick":tick,"generation":7,"event_id":"%s:%s:%s"%[kind,id,tick]}
 value.merge(extra,true)
 return value
func place(id:int=0,tick:int=20,expiry:int=120)->Dictionary:
 return event("mine_placed",id,tick,{"cell":Vector2(2,3),"expires_tick":expiry})
func run()->void:
 var path:String="res://scripts/native_ground_mines.gd"
 ck(ResourceLoader.exists(path),"event-driven native ground mine presenter exists")
 if not ResourceLoader.exists(path):finish();return
 var script=load(path)
 var mines=script.new();root.add_child(mines);mines.reset(7)
 ck(not mines.is_processing() and not mines.is_physics_processing(),"no independent wall-clock or physics progression")
 var original:Array=units.duplicate(true)
 var placed:Dictionary=place();var original_event:Dictionary=placed.duplicate(true)
 mines.consume(placed,units);mines.update_time(0.99)
 ck(mines.diagnostics().active_mines==0,"future mine waits for battle time")
 mines.update_time(1.0)
 ck(mines.diagnostics().active_mines==1,"game placement creates one native mine")
 ck(mines.diagnostics().cached_materials==1,"native material warms exactly once")
 var first:Dictionary=mines.snapshot()
 ck(first.has(0),"snapshot exposes authoritative mine identifier")
 if first.has(0):
  ck(first[0].cell==Vector2(2,3),"mine center follows event cell")
  ck(first[0].native_mesh_count==1,"native prop has one real mesh")
  ck(first[0].mapped_surfaces==1,"native weapon shader overrides source material")
  ck(first[0].bounds.position.y>=0.0049,"mine geometry sits above court")
  ck(absf(first[0].bounds.get_center().x-2)<0.00001 and absf(first[0].bounds.get_center().z-3)<0.00001,"native geometry centers at event cell")
  ck(first[0].bounds.size.x>0.30 and first[0].bounds.size.x<0.34,"native 2.2 initial size and world 1.3 scale applied once")
 mines.update_time(1.0);mines.consume(placed,units);mines.update_time(1.0)
 ck(first==mines.snapshot(),"pause and duplicate event leave same native pose")
 ck(mines.diagnostics().spawned==1,"duplicate event does not allocate another prop")
 ck(units==original and placed==original_event,"presentation never mutates simulation inputs")
 var stale:Dictionary=place(1);stale.generation=6;mines.consume(stale,units);mines.update_time(1.0)
 ck(mines.diagnostics().stale_events==1 and mines.diagnostics().active_mines==1,"stale generation cannot spawn")
 mines.consume(event("mine_triggered",0,30),units);mines.update_time(1.49)
 ck(mines.diagnostics().active_mines==1,"future trigger does not remove early")
 mines.update_time(1.5)
 ck(mines.get_child_count()==0 and mines.diagnostics().active_mines==0,"trigger frees prop without hidden stale nodes")
 # The same mine cannot be resurrected by delayed or differently identified replay.
 placed.event_id="late-duplicate";mines.consume(placed,units);mines.update_time(1.5)
 ck(mines.diagnostics().active_mines==0,"terminal mine cannot resurrect after event replay")
 mines.consume(place(2,40,60),units);mines.update_time(2.0)
 ck(mines.diagnostics().active_mines==1,"new mine identifier may spawn")
 mines.update_time(3.0)
 ck(mines.diagnostics().active_mines==0 and mines.get_child_count()==0,"declared expires_tick removes prop even if expiry delivery is delayed")
 mines.consume(place(3,40,45),units);mines.update_time(3.0)
 ck(mines.diagnostics().active_mines==0,"already-expired late placement never flashes")
 mines.consume(place(4,70,120),units);mines.consume(event("mine_expired",4,80),units);mines.update_time(4.0)
 ck(mines.diagnostics().active_mines==0,"explicit expiry event removes mine")
 mines.consume(place(5,90,150),units);mines.update_time(4.5)
 mines.consume(event("mine_removed",5,91,{"reason":"source_dead"}),units);mines.update_time(4.55)
 ck(mines.diagnostics().active_mines==0,"source-dead mine_removed releases prop")
 mines.reset(7)
 mines.consume(place(6,0,200),units);mines.consume(place(7,0,200),units);mines.update_time(0)
 ck(mines.diagnostics().active_mines==2,"one source can own several native mines")
 mines.consume(event("death",-1,10),units);mines.update_time(0.5)
 ck(mines.diagnostics().active_mines==0 and mines.get_child_count()==0,"death event releases every source-owned mine")
 mines.consume(place(8,15,200),units);mines.update_time(1)
 ck(mines.diagnostics().active_mines==0,"dead source cannot place from late delivery")
 mines.reset(7)
 # Terminal delivery can precede placement; processing is tick-ordered.
 mines.consume(event("mine_triggered",9,30),units);mines.consume(place(9,20,120),units);mines.update_time(1.0)
 ck(mines.diagnostics().active_mines==1,"out-of-order delivery respects placement time")
 mines.update_time(1.5);ck(mines.diagnostics().active_mines==0,"out-of-order terminal closes at its own time")
 mines.reset(7)
 var remove_first:Dictionary=event("mine_removed",10,20);mines.consume(remove_first,units);mines.update_time(1.0)
 mines.consume(place(10,0,200),units);mines.update_time(1.0)
 ck(mines.diagnostics().active_mines==0,"early terminal tombstone blocks delayed placement")
 mines.reset(7);mines.consume(place(11,0,200),units);mines.update_time(0)
 mines.consume(place(12,100,200),units);mines.reset(8)
 ck(mines.get_child_count()==0 and mines.diagnostics().queued_events==0,"reset immediately frees visible and pending mines")
 mines.consume(place(11,0,200),units);mines.update_time(0)
 ck(mines.diagnostics().active_mines==0,"previous generation replay rejected after reset")
 var new_event:Dictionary=place(11,0,200);new_event.generation=8;mines.consume(new_event,units);mines.update_time(0)
 ck(mines.diagnostics().active_mines==1,"new generation can reuse mine identifier")
 mines.reset(7);mines.consume(place(13,0,200),units);mines.update_time(2)
 mines.update_time(1)
 ck(mines.diagnostics().time==2.0,"rewind cannot advance backwards without reset")
 mines.update_time(NAN);ck(mines.diagnostics().time==2.0,"nonfinite battle clock rejected")
 mines.reset(7);var invalid:Dictionary=place(14);invalid.cell=Vector2(NAN,0);mines.consume(invalid,units);mines.update_time(2)
 ck(mines.diagnostics().active_mines==0,"nonfinite placement never adds a prop")
 mines.reset(7)
 var fallback:Dictionary=place(15,0,200);fallback.erase("event_id")
 mines.consume(fallback,units);mines.consume(fallback,units);mines.update_time(0)
 ck(mines.diagnostics().active_mines==1 and mines.diagnostics().spawned==1,"missing event_id has stable lifecycle dedup key")
 var other:Dictionary=place(16,0,200);other.actor_id=2;mines.consume(other,units);mines.update_time(0)
 mines.consume(event("death",-1,10),units);mines.update_time(0.5)
 ck(mines.diagnostics().active_mines==1 and mines.snapshot().has(16),"source death preserves other actor's mines")
 mines.reset(7);mines.consume(place(17,20,200),units);mines.consume(event("mine_triggered",17,20),units);mines.update_time(1)
 ck(mines.get_child_count()==0,"same-tick place and trigger cannot leak visible or hidden props")
 mines.reset(7);mines.consume(place(18,0,200),units);mines.update_time(0)
 mines.consume({"type":"finished","tick":10,"generation":7,"event_id":"finished"},units)
 mines.consume(place(19,20,200),units);mines.update_time(0.5)
 ck(mines.diagnostics().active_mines==0 and mines.get_child_count()==0 and mines.diagnostics().queued_events==0,"finished clears all authoritative mines and pending placements")
 mines.consume(place(20,20,200),units);mines.update_time(1)
 ck(mines.diagnostics().active_mines==0,"late placements cannot resurrect finished battle")
 mines.free();finish()
func finish()->void:
 print("NATIVE_GROUND_MINES ",checks," checks; ",failures," failures")
 quit(1 if failures else 0)
